// Generated by tools/gen_xdll_thunks.py - do not edit.
#include "reach_pch.h"

#include <unordered_map>

namespace {
// WavesLibDLL.dll exports (ordinal -> guest address)
const std::unordered_map<uint32_t, uint32_t> kExports0 = {
    {0x1, 0x8A063A70},
    {0x2, 0x8A04A580},
    {0x3, 0x8A04A538},
    {0xB, 0x8A0634A0},
    {0xC, 0x8A063278},
    {0xE, 0x8A064360},
    {0x17, 0x8A0965C0},
    {0x18, 0x8A0646F8},
    {0x19, 0x8A062CD0},
    {0x1A, 0x8A062CB8},
    {0x1B, 0x8A048EA0},
    {0x1C, 0x8A023F18},
    {0x1D, 0x8A03CFA8},
    {0x1E, 0x8A040768},
    {0x1F, 0x8A03CFA8},
    {0x20, 0x8A0402D8},
    {0x21, 0x8A040420},
    {0x22, 0x8A03CFA8},
    {0x23, 0x8A03FBF0},
    {0x24, 0x8A03FA18},
    {0x25, 0x8A07A1B0},
    {0x26, 0x8A03D508},
    {0x27, 0x8A042A48},
    {0x28, 0x8A07A1B0},
    {0x29, 0x8A040D48},
    {0x2A, 0x8A03CFA8},
    {0x2B, 0x8A03BD08},
    {0x2C, 0x8A03E0F0},
    {0x2D, 0x8A03F9E8},
    {0x2E, 0x8A03FA08},
    {0x2F, 0x8A03F9F0},
    {0x30, 0x8A061CC0},
    {0x31, 0x8A03D610},
    {0x32, 0x8A04A2F8},
    {0x33, 0x8A04A280},
    {0x34, 0x8A04A880},
    {0x35, 0x8A040588},
    {0x36, 0x8A0438C0},
    {0x37, 0x8A03FA00},
    {0x38, 0x8A043980},
    {0x39, 0x8A040530},
    {0x3A, 0x8A03D198},
    {0x3B, 0x8A03D190},
    {0x3C, 0x8A0651B0},
    {0x3D, 0x8A043A40},
    {0x3E, 0x8A065148},
    {0x3F, 0x8A065138},
    {0x40, 0x8A04A700},
    {0x41, 0x8A03CFA8},
    {0x42, 0x8A043768},
    {0x43, 0x8A064810},
    {0x44, 0x8A062DF8},
    {0x45, 0x8A043648},
    {0x46, 0x8A043E50},
    {0x47, 0x8A03AB00},
    {0x48, 0x8A039CE8},
    {0x49, 0x8A043AC8},
    {0x4A, 0x8A043A78},
    {0x4B, 0x8A0429C0},
    {0x4C, 0x8A0633D8},
    {0x4D, 0x8A042990},
    {0x4E, 0x8A03D500},
    {0x50, 0x8A040B08},
    {0x51, 0x8A0433F8},
    {0x52, 0x8A0415E8},
    {0x53, 0x8A041B48},
    {0x54, 0x8A040608},
    {0x55, 0x8A043C80},
    {0x56, 0x8A040DD0},
    {0x57, 0x8A043440},
    {0x58, 0x8A040E88},
    {0x59, 0x8A0436A0},
    {0x5A, 0x8A03E738},
    {0x5B, 0x8A041AA0},
    {0x5C, 0x8A0403C0},
    {0x60, 0x8A03E070},
    {0x61, 0x8A07A398},
    {0x62, 0x8A07A388},
    {0x64, 0x8A07A380},
    {0x65, 0x8A044130},
    {0x67, 0x8A0445D8},
    {0x68, 0x8A0444C0},
    {0x69, 0x8A044140},
    {0x6A, 0x8A043FB0},
    {0x6B, 0x8A0425E8},
    {0x6C, 0x8A043448},
    {0x6D, 0x8A03FF10},
    {0x6E, 0x8A03D600},
    {0x71, 0x8A037650},
    {0x72, 0x8A03D4F8},
    {0x73, 0x8A0401E8},
    {0x74, 0x8A063048},
    {0x75, 0x8A04A208},
    {0x77, 0x8A04B1D8},
    {0x78, 0x8A04B0A8},
    {0x79, 0x8A04AFD0},
    {0x7A, 0x8A04B268},
    {0x7B, 0x8A04AE08},
    {0x7C, 0x8A04A928},
    {0x7D, 0x8A065018},
    {0x7E, 0x8A03FF28},
    {0x7F, 0x8A04B648},
    {0x80, 0x8A04B730},
    {0x81, 0x8A04B420},
    {0x82, 0x8A04A5A0},
    {0x83, 0x8A03B5E8},
    {0x84, 0x8A03B650},
    {0x85, 0x8A044158},
    {0x86, 0x8A063A58},
    {0x87, 0x8A042558},
    {0x88, 0x8A040380},
    {0x89, 0x8A040470},
    {0x8A, 0x8A0404B0},
    {0x8B, 0x8A0404F0},
    {0x8C, 0x8A0400B0},
    {0x8D, 0x8A04AE90},
    {0x8E, 0x8A04A628},
    {0x8F, 0x8A043C90},
    {0x90, 0x8A043D38},
    {0x91, 0x8A07A1B0},
};

uint32_t ResolveThunkTarget(uint8_t* base, uint32_t thunk) {
  uint32_t w0 = REX_LOAD_U32(thunk);
  if ((w0 >> 26) == 15) {
    uint32_t w1 = REX_LOAD_U32(thunk + 4);
    uint32_t target = (w0 & 0xFFFF) << 16;
    return (w1 >> 26) == 14
        ? target + static_cast<uint32_t>(static_cast<int32_t>(static_cast<int16_t>(w1 & 0xFFFF)))
        : target | (w1 & 0xFFFF);
  }
  uint32_t lib = (w0 >> 16) & 0xFF, ordinal = w0 & 0xFFFF;
  const std::unordered_map<uint32_t, uint32_t>* table = nullptr;
  switch (lib) {
    case 0: table = &kExports0; break;
  }
  if (table) {
    if (auto it = table->find(ordinal); it != table->end()) return it->second;
  }
  REXLOG_ERROR("xdll thunk {:08X}: unresolved import record {:08X}", thunk, w0);
  return 0;
}
}  // namespace

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DACC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DACC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DADC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DADC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DAEC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DAEC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DAFC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DAFC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB0C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB0C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB1C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB1C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB2C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB2C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB3C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB3C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB4C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB4C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB5C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB5C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB6C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB6C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB7C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB7C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB8C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB8C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DB9C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DB9C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBAC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBAC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBBC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBBC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBCC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBCC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBDC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBDC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBEC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBEC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DBFC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DBFC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC0C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC0C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC1C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC1C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC2C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC2C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC3C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC3C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC4C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC4C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC5C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC5C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC6C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC6C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC7C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC7C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC8C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC8C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DC9C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DC9C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCAC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCAC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCBC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCBC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCCC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCCC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCDC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCDC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCEC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCEC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DCFC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DCFC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943DD0C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943DD0C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E32C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E32C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E31C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E31C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E30C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E30C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2FC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2FC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2EC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2EC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2DC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2DC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2CC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2CC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2BC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2BC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E2AC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E2AC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E29C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E29C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E28C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E28C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E27C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E27C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E26C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E26C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E25C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E25C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E24C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E24C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E23C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E23C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E22C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E22C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E21C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E21C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E20C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E20C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1FC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1FC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1EC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1EC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1DC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1DC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1CC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1CC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1BC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1BC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E1AC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E1AC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E19C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E19C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E18C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E18C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E17C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E17C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E16C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E16C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E15C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E15C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E14C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E14C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E13C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E13C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E12C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E12C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E33C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E33C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E11C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E11C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E10C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E10C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0FC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0FC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0EC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0EC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0DC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0DC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0CC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0CC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0BC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0BC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E0AC) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E0AC);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E09C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E09C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8943E08C) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8943E08C);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

