// Generated by tools/gen_xdll_thunks.py - do not edit.
#include "reach_pch.h"

#include <unordered_map>

namespace {
// WavesLibDLL.dll exports (ordinal -> guest address)
const std::unordered_map<uint32_t, uint32_t> kExports0 = {
    {0x1, 0x8A063A70},
    {0x2, 0x8A04A580},
    {0x3, 0x8A04A538},
    {0xB, 0x8A0634A0},
    {0xC, 0x8A063278},
    {0xE, 0x8A064360},
    {0x17, 0x8A0965C0},
    {0x18, 0x8A0646F8},
    {0x19, 0x8A062CD0},
    {0x1A, 0x8A062CB8},
    {0x1B, 0x8A048EA0},
    {0x1C, 0x8A023F18},
    {0x1D, 0x8A03CFA8},
    {0x1E, 0x8A040768},
    {0x1F, 0x8A03CFA8},
    {0x20, 0x8A0402D8},
    {0x21, 0x8A040420},
    {0x22, 0x8A03CFA8},
    {0x23, 0x8A03FBF0},
    {0x24, 0x8A03FA18},
    {0x25, 0x8A07A1B0},
    {0x26, 0x8A03D508},
    {0x27, 0x8A042A48},
    {0x28, 0x8A07A1B0},
    {0x29, 0x8A040D48},
    {0x2A, 0x8A03CFA8},
    {0x2B, 0x8A03BD08},
    {0x2C, 0x8A03E0F0},
    {0x2D, 0x8A03F9E8},
    {0x2E, 0x8A03FA08},
    {0x2F, 0x8A03F9F0},
    {0x30, 0x8A061CC0},
    {0x31, 0x8A03D610},
    {0x32, 0x8A04A2F8},
    {0x33, 0x8A04A280},
    {0x34, 0x8A04A880},
    {0x35, 0x8A040588},
    {0x36, 0x8A0438C0},
    {0x37, 0x8A03FA00},
    {0x38, 0x8A043980},
    {0x39, 0x8A040530},
    {0x3A, 0x8A03D198},
    {0x3B, 0x8A03D190},
    {0x3C, 0x8A0651B0},
    {0x3D, 0x8A043A40},
    {0x3E, 0x8A065148},
    {0x3F, 0x8A065138},
    {0x40, 0x8A04A700},
    {0x41, 0x8A03CFA8},
    {0x42, 0x8A043768},
    {0x43, 0x8A064810},
    {0x44, 0x8A062DF8},
    {0x45, 0x8A043648},
    {0x46, 0x8A043E50},
    {0x47, 0x8A03AB00},
    {0x48, 0x8A039CE8},
    {0x49, 0x8A043AC8},
    {0x4A, 0x8A043A78},
    {0x4B, 0x8A0429C0},
    {0x4C, 0x8A0633D8},
    {0x4D, 0x8A042990},
    {0x4E, 0x8A03D500},
    {0x50, 0x8A040B08},
    {0x51, 0x8A0433F8},
    {0x52, 0x8A0415E8},
    {0x53, 0x8A041B48},
    {0x54, 0x8A040608},
    {0x55, 0x8A043C80},
    {0x56, 0x8A040DD0},
    {0x57, 0x8A043440},
    {0x58, 0x8A040E88},
    {0x59, 0x8A0436A0},
    {0x5A, 0x8A03E738},
    {0x5B, 0x8A041AA0},
    {0x5C, 0x8A0403C0},
    {0x60, 0x8A03E070},
    {0x61, 0x8A07A398},
    {0x62, 0x8A07A388},
    {0x64, 0x8A07A380},
    {0x65, 0x8A044130},
    {0x67, 0x8A0445D8},
    {0x68, 0x8A0444C0},
    {0x69, 0x8A044140},
    {0x6A, 0x8A043FB0},
    {0x6B, 0x8A0425E8},
    {0x6C, 0x8A043448},
    {0x6D, 0x8A03FF10},
    {0x6E, 0x8A03D600},
    {0x71, 0x8A037650},
    {0x72, 0x8A03D4F8},
    {0x73, 0x8A0401E8},
    {0x74, 0x8A063048},
    {0x75, 0x8A04A208},
    {0x77, 0x8A04B1D8},
    {0x78, 0x8A04B0A8},
    {0x79, 0x8A04AFD0},
    {0x7A, 0x8A04B268},
    {0x7B, 0x8A04AE08},
    {0x7C, 0x8A04A928},
    {0x7D, 0x8A065018},
    {0x7E, 0x8A03FF28},
    {0x7F, 0x8A04B648},
    {0x80, 0x8A04B730},
    {0x81, 0x8A04B420},
    {0x82, 0x8A04A5A0},
    {0x83, 0x8A03B5E8},
    {0x84, 0x8A03B650},
    {0x85, 0x8A044158},
    {0x86, 0x8A063A58},
    {0x87, 0x8A042558},
    {0x88, 0x8A040380},
    {0x89, 0x8A040470},
    {0x8A, 0x8A0404B0},
    {0x8B, 0x8A0404F0},
    {0x8C, 0x8A0400B0},
    {0x8D, 0x8A04AE90},
    {0x8E, 0x8A04A628},
    {0x8F, 0x8A043C90},
    {0x90, 0x8A043D38},
    {0x91, 0x8A07A1B0},
};

uint32_t ResolveThunkTarget(uint8_t* base, uint32_t thunk) {
  uint32_t w0 = REX_LOAD_U32(thunk);
  if ((w0 >> 26) == 15) {
    uint32_t w1 = REX_LOAD_U32(thunk + 4);
    uint32_t target = (w0 & 0xFFFF) << 16;
    return (w1 >> 26) == 14
        ? target + static_cast<uint32_t>(static_cast<int32_t>(static_cast<int16_t>(w1 & 0xFFFF)))
        : target | (w1 & 0xFFFF);
  }
  uint32_t lib = (w0 >> 16) & 0xFF, ordinal = w0 & 0xFFFF;
  const std::unordered_map<uint32_t, uint32_t>* table = nullptr;
  switch (lib) {
    case 0: table = &kExports0; break;
  }
  if (table) {
    if (auto it = table->find(ordinal); it != table->end()) return it->second;
  }
  REXLOG_ERROR("xdll thunk {:08X}: unresolved import record {:08X}", thunk, w0);
  return 0;
}
}  // namespace

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934894) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934894);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348A4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348A4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348B4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348B4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348C4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348C4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348D4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348D4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348E4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348E4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9348F4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9348F4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934904) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934904);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934914) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934914);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934924) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934924);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934934) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934934);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934944) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934944);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934954) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934954);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934964) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934964);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934974) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934974);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934984) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934984);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934994) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934994);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349A4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349A4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349B4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349B4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349C4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349C4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349D4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349D4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349E4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349E4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9349F4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9349F4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A04) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A04);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A14) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A14);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A24) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A24);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A34) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A34);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A44) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A44);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A54) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A54);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A64) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A64);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A74) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A74);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A84) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A84);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934A94) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934A94);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934AA4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934AA4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934AB4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934AB4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934AC4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934AC4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9350D4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9350D4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9350C4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9350C4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9350B4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9350B4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9350A4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9350A4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935094) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935094);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935084) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935084);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935074) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935074);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935064) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935064);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935054) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935054);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935044) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935044);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935034) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935034);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935024) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935024);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935014) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935014);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B935004) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B935004);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FF4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FF4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FE4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FE4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FD4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FD4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FC4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FC4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FB4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FB4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934FA4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934FA4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F94) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F94);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F84) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F84);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F74) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F74);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F64) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F64);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F54) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F54);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F44) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F44);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F34) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F34);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F24) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F24);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F14) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F14);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934F04) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934F04);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934EF4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934EF4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934EE4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934EE4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934ED4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934ED4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B9350E4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B9350E4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934EC4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934EC4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934EB4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934EB4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934EA4) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934EA4);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E94) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E94);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E84) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E84);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E74) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E74);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E64) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E64);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E54) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E54);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E44) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E44);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

// WavesLibDLL.dll
DEFINE_REX_FUNC(sub_8B934E34) {
  REX_FUNC_PROLOGUE();
  uint32_t target = ResolveThunkTarget(base, 0x8B934E34);
  ctx.r11.u64 = target;
  ctx.ctr.u64 = target;
  REX_CALL_INDIRECT_FUNC(target);
}

