#!/usr/bin/env python3
"""Emit C++ bodies for guest-DLL -> guest-DLL import thunks.

ReXGlue codegen declares these thunks but only implements imports from
xboxkrnl/xam, and the runtime loader leaves the guest import records
unpatched. Each body therefore decodes its own import record
(0x01LLOOOO: library index LL, ordinal OOOO) and calls the export, using an
ordinal table baked from the exporting module's XEX export table. Guest DLLs
are recompiled for their fixed load address, so the addresses are static.

Usage: gen_xdll_thunks.py GAME_ROOT MODULE_XEX GENERATED_DIR OUT_CPP
"""
import os
import re
import struct
import sys

SYSTEM_LIBS = {"xboxkrnl.exe", "xam.xex", "xbdm.xex"}


def opt_header(d, key):
    for i in range(struct.unpack_from(">I", d, 0x14)[0]):
        k, v = struct.unpack_from(">II", d, 0x18 + i * 8)
        if k == key:
            return v
    return None


def import_libraries(d):
    val = opt_header(d, 0x000103FF)
    if val is None:
        return []
    size, str_size, _ = struct.unpack_from(">III", d, val)
    names = [n.decode() for n in d[val + 12 : val + 12 + str_size].split(b"\0") if n]
    off, libs = val + 12 + str_size, []
    while off < val + size:
        lib_size = struct.unpack_from(">I", d, off)[0]
        name_index, rec_count = struct.unpack_from(">HH", d, off + 0x24)
        libs.append((names[name_index], struct.unpack_from(f">{rec_count}I", d, off + 0x28)))
        off += lib_size
    return libs


def decompressed_image(path):
    """Ask the GhidraMCP server (which ran the XEX loader) for image bytes."""
    import json
    import urllib.request

    def read(program, addr, n):
        url = f"http://127.0.0.1:8089/read_memory?address={addr:#x}&length={n}&program={program}"
        return bytes(json.loads(urllib.request.urlopen(url, timeout=60).read())["data"])

    return read


def export_table(game_root, lib_name):
    for dirpath, _, files in os.walk(game_root):
        for f in files:
            if f.lower() == lib_name.lower():
                path = os.path.join(dirpath, f)
                d = open(path, "rb").read()
                sec = struct.unpack_from(">I", d, 0x10)[0]
                table = struct.unpack_from(">I", d, sec + 0x160)[0]
                read = decompressed_image(path)
                program = "/xbox360/" + f
                hdr = read(program, table, 0x2C)
                base_hi, count, ord_base = struct.unpack_from(">III", hdr, 0x20)
                offs = struct.unpack(f">{count}I", read(program, table + 0x2C, count * 4))
                return {ord_base + i: ((base_hi << 16) + o) & 0xFFFFFFFF for i, o in enumerate(offs) if o}
    raise SystemExit(f"exporting module {lib_name} not found under {game_root}")


def main():
    game_root, xex, gen_dir, out = sys.argv[1:5]
    d = open(xex, "rb").read()
    pch = open(f"{gen_dir}/reach_pch.h").read()
    code_base = int(re.search(r"REX_CODE_BASE (0x[0-9A-Fa-f]+)", pch).group(1), 16)
    code_size = int(re.search(r"REX_CODE_SIZE (0x[0-9A-Fa-f]+)", pch).group(1), 16)
    declared = set(re.findall(r"DECLARE_REX_FUNC\((sub_[0-9A-F]{8})\)", open(f"{gen_dir}/reach_funcs.h").read()))

    libs = import_libraries(d)
    tables, thunks = {}, []
    for index, (lib, recs) in enumerate(libs):
        if lib.lower() in SYSTEM_LIBS:
            continue
        tables[index] = (lib, export_table(game_root, lib))
        for addr in recs:
            if code_base <= addr < code_base + code_size and f"sub_{addr:08X}" in declared:
                thunks.append((index, lib, addr))

    with open(out, "w") as f:
        f.write("// Generated by tools/gen_xdll_thunks.py - do not edit.\n")
        f.write("#include \"reach_pch.h\"\n\n#include <unordered_map>\n\n")
        f.write("namespace {\n")
        for index, (lib, table) in tables.items():
            f.write(f"// {lib} exports (ordinal -> guest address)\n")
            f.write(f"const std::unordered_map<uint32_t, uint32_t> kExports{index} = {{\n")
            for o, a in sorted(table.items()):
                f.write(f"    {{0x{o:X}, 0x{a:08X}}},\n")
            f.write("};\n\n")
        f.write("uint32_t ResolveThunkTarget(uint8_t* base, uint32_t thunk) {\n")
        f.write("  uint32_t w0 = REX_LOAD_U32(thunk);\n")
        f.write("  if ((w0 >> 26) == 15) {\n")
        f.write("    uint32_t w1 = REX_LOAD_U32(thunk + 4);\n")
        f.write("    uint32_t target = (w0 & 0xFFFF) << 16;\n")
        f.write("    return (w1 >> 26) == 14\n")
        f.write("        ? target + static_cast<uint32_t>(static_cast<int32_t>(static_cast<int16_t>(w1 & 0xFFFF)))\n")
        f.write("        : target | (w1 & 0xFFFF);\n")
        f.write("  }\n")
        f.write("  uint32_t lib = (w0 >> 16) & 0xFF, ordinal = w0 & 0xFFFF;\n")
        f.write("  const std::unordered_map<uint32_t, uint32_t>* table = nullptr;\n")
        f.write("  switch (lib) {\n")
        for index in tables:
            f.write(f"    case {index}: table = &kExports{index}; break;\n")
        f.write("  }\n")
        f.write("  if (table) {\n")
        f.write("    if (auto it = table->find(ordinal); it != table->end()) return it->second;\n")
        f.write("  }\n")
        f.write("  REXLOG_ERROR(\"xdll thunk {:08X}: unresolved import record {:08X}\", thunk, w0);\n")
        f.write("  return 0;\n")
        f.write("}\n")
        f.write("}  // namespace\n\n")
        for index, lib, addr in thunks:
            f.write(f"// {lib}\n")
            f.write(f"DEFINE_REX_FUNC(sub_{addr:08X}) {{\n")
            f.write("  REX_FUNC_PROLOGUE();\n")
            f.write(f"  uint32_t target = ResolveThunkTarget(base, 0x{addr:08X});\n")
            f.write("  ctx.r11.u64 = target;\n")
            f.write("  ctx.ctr.u64 = target;\n")
            f.write("  REX_CALL_INDIRECT_FUNC(target);\n")
            f.write("}\n\n")
    print(f"{xex}: {len(thunks)} thunks, {sum(len(t) for _, t in tables.values())} exports baked -> {out}")


if __name__ == "__main__":
    main()
