#!/usr/bin/env bash
# Copy reach-recomp/generated/ into the PRIVATE DecompiledHaloReach-generated checkout and push.
# The generated C++ is translated game code: it must never be committed to this public repo.
# Usage: tools/sync_generated_repo.sh [checkout-dir]   (default ~/DecompiledHaloReach-generated)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$HOME/DecompiledHaloReach-generated}"
MAIN="$(git -C "$ROOT" rev-parse --short HEAD)"
SDK="$("${REXSDK:-$HOME/rexglue-sdk-nightly/0.10.0.24/linux-amd64}/bin/rexglue" --version 2>/dev/null | head -1)"

[ -d "$DEST/.git" ] || { echo "no git checkout at $DEST" >&2; exit 1; }
[ "$(gh repo view "$(git -C "$DEST" remote get-url origin)" --json visibility -q .visibility)" = PRIVATE ] \
    || { echo "refusing: $DEST's origin is not a private repository" >&2; exit 1; }

# The private repo keeps its own README and CI workflow (.github), which are not codegen output.
rsync -a --delete --exclude .git --exclude .github --exclude README.md "$ROOT/reach-recomp/generated/" "$DEST/"
sed -i -E "s/(From manifest\/hints at DecompiledHaloReach commit: ).*/\1$MAIN/; s/(Generated by: ReXGlue SDK ).*/\1$SDK/" "$DEST/README.md"
cd "$DEST"
git add -A
if git diff --cached --quiet; then echo "generated code unchanged"; exit 0; fi
git -c user.name=agent -c user.email=agent@local commit -q -m "Codegen output for DecompiledHaloReach@$MAIN ($SDK)"
git push -q origin HEAD
echo "pushed generated code for $MAIN"
